apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yeobi
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: domain.json
    target:
      kind: Ingress
      name: compile-ingress
images:
  - name: yeobi/compile-server
    newTag: latest
# 2025.03.27 21:13
